cursor = '▇'
blinking-cursor = false

[window]
width = 800
height = 600
mode = "Maximized"
foreground-opacity = 1.0
background-opacity = 1.0
blur = false
decorations = "Enabled"

[fonts]
family = "Menlo"
size = 14

[renderer]
performance = "High"
backend = "Automatic"
disable-renderer-when-unfocused = true
